### ISSUE TITLE
Console giriş yeri gizlenmiyor, vs. Öneriler

### ISSUE THREAD

**Issue by abdurrahmanekr** [abdurrahmanekr/kodalog#1]
• Konsol tasarımında giriş yaptığımız yer sürekli açık durumda kapatıp açınca sabit duruyor bunun giderilmesi gerekir.
• Tasarımın google chrome dev. tools'a benzetilmesi tarafındayım. Bu konu burada tartışılabilir.
• Console komut giriş yerinin textarea olması yükseklik ayarının yapılmasında kolaylık sağlar. bunu textarea yapısına çevirelim

Diyeceklerim bu kadardı. Teşekkürler :relieved:

**Comment by sametcodes** [comment]
Textarea yerine **contenteditable** div nesnesi kullanılabilir, son güncellemede gerekli şekilde düzelttim. Textarea olduğu taktirde otomatik yükseklik işlevi, yani kullanıcı yeni satırlar girdikçe textarea nesnesinin de yüksekliği bununla birlikte artması gerekecekti. Bunu Javascript tarafında yönetmek biraz zorlu olabilir, gerekli araştırmaları yaptım. Özellikle yüksekliği artıran fonksiyon, textarea içerisine onkeydown işlevi ile tetiklendiğinden tarayıcıyı zorlamakta. Bunun yerine contenteditable bir div kullanmak daha mantıklı diye düşünüyorum. Özellikle çoklu satır ile komutların girilebilmesine ve sadece **shift+enter** ile alt satıra geçilebilmesine olanak sağlandı. Tarayıcının konsol girdileri ile aynı durumda şuan için. Son güncellemeye bakabilirsin.

Son olarak sürükle-bırak işlevi eklenmiş bulunuyor. Salt javascript ile ikon üzerine tıklama ve basılı tutmayı yakalamaya çalışarak sürükle-bırak işlevini ekledim. Şuan için kullanılabilir durumda. Platform ve tarayıcıya göre çıkabilecek sorunlar için ileriki vakitlerde güncellemeler yapılabilir.
